Repository Team-ISFive/UsEarth_ISFive, pull requests merged in 2023-08, with the labels that each got.

#4 Ue 3 member maker entity create
  src/main/java/com/isfive/usearth/UsEarthApplication.java
  src/main/java/com/isfive/usearth/entity/BaseEntity.java
  src/main/java/com/isfive/usearth/entity/Member.java
  src/main/java/com/isfive/usearth/entity/Role.java
  src/main/java/com/isfive/usearth/entity/maker/BusinessInformation.java
  src/main/java/com/isfive/usearth/entity/maker/CorporateBusiness.java
  src/main/java/com/isfive/usearth/entity/maker/Individual.java
  src/main/java/com/isfive/usearth/entity/maker/Maker.java
  src/main/java/com/isfive/usearth/entity/maker/PersonalBusiness.java
Labels: feature

#3 UE 4 Project Entity create
  src/main/java/com/isfive/usearth/entity/Address.java
  src/main/java/com/isfive/usearth/entity/Delivery.java
  src/main/java/com/isfive/usearth/entity/DeliveryStatus.java
  src/main/java/com/isfive/usearth/entity/Funding.java
  src/main/java/com/isfive/usearth/entity/FundingReward.java
  src/main/java/com/isfive/usearth/entity/FundingStatus.java
  src/main/java/com/isfive/usearth/entity/Option.java
  src/main/java/com/isfive/usearth/entity/OptionValue.java
  src/main/java/com/isfive/usearth/entity/Project.java
  src/main/java/com/isfive/usearth/entity/Reward.java
  src/main/java/com/isfive/usearth/entity/RewardSku.java
  src/main/java/com/isfive/usearth/entity/SkuValue.java
  src/main/java/com/isfive/usearth/entity/Tag.java
Labels: feature

#8 Ue 6 file image entity create
  src/main/java/com/isfive/usearth/entity/ActivityFileImage.java
  src/main/java/com/isfive/usearth/entity/FileImage.java
  src/main/java/com/isfive/usearth/entity/PostComment.java
  src/main/java/com/isfive/usearth/entity/PostFileImage.java
  src/main/java/com/isfive/usearth/entity/PostLike.java
  src/main/java/com/isfive/usearth/entity/ProjectComment.java
  src/main/java/com/isfive/usearth/entity/ProjectFileImage.java
  src/main/java/com/isfive/usearth/entity/ProjectLike.java
Labels: feature

#9 feat: Chat 연관관계 설정
  src/main/java/com/isfive/usearth/entity/ChatMessage.java
  src/main/java/com/isfive/usearth/entity/ChatRoom.java
  src/main/java/com/isfive/usearth/entity/ChatRoomAppend.java
Labels: feature

#14 fix : SkuValue, RewardSku 연관관계 수정, Period 관련 네이밍 수정
  src/main/java/com/isfive/usearth/Activity.java
  src/main/java/com/isfive/usearth/Period.java
  src/main/java/com/isfive/usearth/entity/RewardSku.java
  src/main/java/com/isfive/usearth/entity/SkuValue.java
Labels: bug, feature, fix

#15 feat : Option의 테이블명 수정, mysql 연결
  build.gradle
  src/main/java/com/isfive/usearth/entity/Option.java
  src/main/java/com/isfive/usearth/entity/OptionValue.java
  src/main/resources/application.yml
Labels: feature, fix

#18 Ue 14 project list select
  .gitignore
  build.gradle
  src/main/java/com/isfive/usearth/domain/funding/entity/FundingReward.java
  src/main/java/com/isfive/usearth/domain/project/ProjectController.java
  src/main/java/com/isfive/usearth/domain/project/ProjectRepository.java
  src/main/java/com/isfive/usearth/domain/project/ProjectResponse.java
  src/main/java/com/isfive/usearth/domain/project/ProjectService.java
  src/main/java/com/isfive/usearth/domain/project/entity/Option.java
  src/main/java/com/isfive/usearth/domain/project/entity/OptionValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/entity/ProjectComment.java
  src/main/java/com/isfive/usearth/domain/project/entity/ProjectFileImage.java
  src/main/java/com/isfive/usearth/domain/project/entity/ProjectLike.java
  src/main/java/com/isfive/usearth/domain/project/entity/Reward.java
  src/main/java/com/isfive/usearth/domain/project/entity/RewardSku.java
  src/main/java/com/isfive/usearth/domain/project/entity/SkuValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/Tag.java
  src/test/java/com/isfive/usearth/domain/project/ProjectControllerTest.java
Labels: feature

#20 Ue 13 project create
  .gitignore
  src/main/java/com/isfive/usearth/domain/common/FileImage.java
  src/main/java/com/isfive/usearth/domain/common/Period.java
  src/main/java/com/isfive/usearth/domain/maker/entity/Maker.java
  src/main/java/com/isfive/usearth/domain/project/ProjectController.java
  src/main/java/com/isfive/usearth/domain/project/ProjectService.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectRegisterDto.java
  src/main/java/com/isfive/usearth/domain/project/dto/RewardRegisterDto.java
  src/main/java/com/isfive/usearth/domain/project/entity/Option.java
  src/main/java/com/isfive/usearth/domain/project/entity/OptionValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/entity/ProjectFileImage.java
  src/main/java/com/isfive/usearth/domain/project/entity/Reward.java
  src/main/java/com/isfive/usearth/domain/project/entity/RewardSku.java
  src/main/java/com/isfive/usearth/domain/project/entity/SkuValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/Tag.java
  src/main/java/com/isfive/usearth/domain/project/repository/OptionRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/OptionValueRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/ProjectRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/RewardRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/RewardSkuRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/SkuValueRespository.java
  src/main/java/com/isfive/usearth/domain/project/repository/TagRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/FileImageService.java
  src/main/java/com/isfive/usearth/domain/project/service/OptionService.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/domain/project/service/RewardService.java
  src/main/java/com/isfive/usearth/domain/project/service/TagService.java
  src/main/java/com/isfive/usearth/domain/project/webDto/ProjectCreateDto.java
Labels: feature

#24 Ue 46 post create select
  build.gradle
  src/main/java/com/isfive/usearth/domain/board/dto/PostResponse.java
  src/main/java/com/isfive/usearth/domain/board/entity/Post.java
  src/main/java/com/isfive/usearth/domain/board/repository/BoardRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostRepository.java
  src/main/java/com/isfive/usearth/domain/board/service/PostService.java
  src/main/java/com/isfive/usearth/domain/maker/service/MakerService.java
  src/main/java/com/isfive/usearth/domain/member/entity/Member.java
  src/main/java/com/isfive/usearth/exception/ErrorCode.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/test/java/com/isfive/usearth/web/board/PostControllerTest.java
Labels: feature

#25 Ue 45 maker register refactoring
  build.gradle
  src/main/java/com/isfive/usearth/domain/maker/dto/MakerResponse.java
  src/main/java/com/isfive/usearth/domain/maker/entity/Individual.java
  src/main/java/com/isfive/usearth/domain/maker/entity/Maker.java
  src/main/java/com/isfive/usearth/domain/maker/entity/PersonalBusiness.java
  src/main/java/com/isfive/usearth/domain/maker/repository/CorporateBusinessRepository.java
  src/main/java/com/isfive/usearth/domain/maker/repository/IndividualRepository.java
  src/main/java/com/isfive/usearth/domain/maker/repository/MakerRepository.java
  src/main/java/com/isfive/usearth/domain/maker/repository/PersonalBusinessRepository.java
  src/main/java/com/isfive/usearth/domain/maker/service/MakerService.java
  src/main/java/com/isfive/usearth/web/maker/MakerController.java
  src/main/java/com/isfive/usearth/web/maker/dto/MakerRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/MakerRegisterRequest.java
  src/main/java/com/isfive/usearth/web/maker/dto/MakerUpdate.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/CorporateRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/IndividualRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/MakerRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/PersonalRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/register_request/BusinessMakerRequest.java
  src/main/java/com/isfive/usearth/web/maker/dto/register_request/MakerRegisterRequest.java
Labels: feature, refactor

#26 Ue 47 post like
  src/main/java/com/isfive/usearth/domain/board/dto/PostResponse.java
  src/main/java/com/isfive/usearth/domain/board/dto/PostsResponse.java
  src/main/java/com/isfive/usearth/domain/board/entity/Post.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostLike.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostLikeRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostRepository.java
  src/main/java/com/isfive/usearth/domain/board/service/PostService.java
  src/main/java/com/isfive/usearth/domain/member/entity/Member.java
  src/main/java/com/isfive/usearth/exception/ErrorCode.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/test/java/com/isfive/usearth/domain/board/service/PostServiceTest.java
  src/test/java/com/isfive/usearth/web/board/PostControllerTest.java
Labels: feature

#27 Ue 13 project create
  src/main/java/com/isfive/usearth/domain/common/FileImageService.java
  src/main/java/com/isfive/usearth/domain/common/Period.java
  src/main/java/com/isfive/usearth/domain/maker/repository/MakerRepository.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectCreate.java
  src/main/java/com/isfive/usearth/domain/project/dto/RewardCreate.java
  src/main/java/com/isfive/usearth/domain/project/entity/Option.java
  src/main/java/com/isfive/usearth/domain/project/entity/OptionValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/entity/ProjectFileImage.java
  src/main/java/com/isfive/usearth/domain/project/entity/Reward.java
  src/main/java/com/isfive/usearth/domain/project/entity/RewardSku.java
  src/main/java/com/isfive/usearth/domain/project/entity/SkuValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/Tag.java
  src/main/java/com/isfive/usearth/domain/project/repository/OptionValueRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/ProjectFileImageRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/OptionService.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/domain/project/service/RewardService.java
  src/main/java/com/isfive/usearth/domain/project/service/TagService.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectCreateDto.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectRegister.java
  src/main/java/com/isfive/usearth/web/project/dto/RewardRegister.java
Labels: feature

#29 Ue 48 comment create
  src/main/java/com/isfive/usearth/domain/board/annotation/Retry.java
  src/main/java/com/isfive/usearth/domain/board/aop/RetryAspect.java
  src/main/java/com/isfive/usearth/domain/board/dto/PostsResponse.java
  src/main/java/com/isfive/usearth/domain/board/entity/Post.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostComment.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostCommentRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostQueryRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostRepositoryImpl.java
  src/main/java/com/isfive/usearth/domain/board/service/PostCommentService.java
  src/main/java/com/isfive/usearth/domain/board/service/PostService.java
  src/main/java/com/isfive/usearth/web/board/PostCommentController.java
  src/main/java/com/isfive/usearth/web/board/dto/PostCommentCreateRequest.java
  src/test/java/com/isfive/usearth/domain/board/service/PostCommentServiceTest.java
  src/test/java/com/isfive/usearth/domain/board/service/PostServiceTest.java
  src/test/java/com/isfive/usearth/web/board/PostCommentControllerTest.java
Labels: feature

#31 Ue 16 project update
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/maker/entity/Maker.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectUpdate.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/repository/ProjectFileImageRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenFilter.java
  src/main/java/com/isfive/usearth/web/maker/MakerController.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectCreateDto.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectModify.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectRegister.java
  src/main/java/com/isfive/usearth/web/project/dto/RewardRegister.java
Labels: feature

#30 Ue 51 reply
  src/main/java/com/isfive/usearth/config/QueryDslConfig.java
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/board/dto/PostCommentResponse.java
  src/main/java/com/isfive/usearth/domain/board/dto/PostResponse.java
  src/main/java/com/isfive/usearth/domain/board/entity/Post.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostComment.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostFileImage.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostCommentRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostFileImageRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/PostLikeRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/post/PostQueryRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/post/PostRepository.java
  src/main/java/com/isfive/usearth/domain/board/repository/post/PostRepositoryImpl.java
  src/main/java/com/isfive/usearth/domain/board/service/PostCommentService.java
  src/main/java/com/isfive/usearth/domain/board/service/PostService.java
  src/main/java/com/isfive/usearth/domain/common/FileImageService.java
  src/main/java/com/isfive/usearth/domain/member/entity/Member.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenFilter.java
  src/main/java/com/isfive/usearth/web/board/PostCommentController.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/test/java/com/isfive/usearth/UsEarthApplicationTests.java
  src/test/java/com/isfive/usearth/domain/board/service/PostCommentServiceTest.java
  src/test/java/com/isfive/usearth/domain/board/service/PostServiceTest.java
  src/test/java/com/isfive/usearth/web/board/PostCommentControllerTest.java
  src/test/java/com/isfive/usearth/web/board/PostControllerTest.java
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
Labels: feature

#32 fix : 오류 수정
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
Labels: fix

#33 Test project create
  src/main/java/com/isfive/usearth/domain/maker/entity/Maker.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectCreate.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectUpdate.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectModify.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectRegister.java
  src/test/java/com/isfive/usearth/domain/project/service/ProjectServiceTest.java
Labels: test

#34 UE-49-Project-refactoring
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectCreate.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectUpdate.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/repository/ProjectRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/SkuValueRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/OptionService.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenFilter.java
  src/main/java/com/isfive/usearth/exception/ErrorCode.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectModify.java
Labels: refactor

#35 Ue 15 project select one
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectResponse.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectsResponse.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/entity/Reward.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/test/java/com/isfive/usearth/domain/project/service/ProjectServiceTest.java
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
Labels: feature

#37 Ue 53 rewards select
  src/main/java/com/isfive/usearth/domain/common/Result.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectResponse.java
  src/main/java/com/isfive/usearth/domain/project/dto/RewardSkuResponse.java
  src/main/java/com/isfive/usearth/domain/project/dto/RewardsResponse.java
  src/main/java/com/isfive/usearth/domain/project/entity/OptionValue.java
  src/main/java/com/isfive/usearth/domain/project/entity/RewardSku.java
  src/main/java/com/isfive/usearth/domain/project/entity/SkuValue.java
  src/main/java/com/isfive/usearth/domain/project/repository/RewardRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/RewardService.java
  src/main/java/com/isfive/usearth/web/project/RewardController.java
  src/test/java/com/isfive/usearth/domain/project/service/ProjectServiceTest.java
  src/test/java/com/isfive/usearth/web/project/RewardControllerTest.java
Labels: feature

#38 Refactor
  src/main/java/com/isfive/usearth/domain/member/entity/Member.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectsResponse.java
  src/main/java/com/isfive/usearth/domain/project/repository/ProjectRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/RewardRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/RewardSkuRepository.java
  src/main/java/com/isfive/usearth/domain/project/repository/SkuValueRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/OptionService.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/domain/project/service/RewardService.java
  src/test/java/com/isfive/usearth/domain/board/service/PostCommentServiceTest.java
  src/test/java/com/isfive/usearth/web/board/PostCommentControllerTest.java
  src/test/java/com/isfive/usearth/web/board/PostControllerTest.java
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
  src/test/java/com/isfive/usearth/web/project/RewardControllerTest.java
Labels: refactor

#39 Ue 23 funding
  src/main/java/com/isfive/usearth/domain/funding/dto/DeliveryRegister.java
  src/main/java/com/isfive/usearth/domain/funding/dto/RewardSkuRegister.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Address.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Delivery.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Funding.java
  src/main/java/com/isfive/usearth/domain/funding/entity/FundingRewardSku.java
  src/main/java/com/isfive/usearth/domain/funding/repository/FundingRepository.java
  src/main/java/com/isfive/usearth/domain/funding/service/FundingService.java
  src/main/java/com/isfive/usearth/domain/project/entity/RewardSku.java
  src/main/java/com/isfive/usearth/domain/project/repository/RewardSkuRepository.java
  src/main/java/com/isfive/usearth/web/funding/FundingController.java
  src/main/java/com/isfive/usearth/web/funding/dto/DeliveryRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/FundingRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/RewardSkuRequest.java
  src/test/java/com/isfive/usearth/web/funding/FundingControllerTest.java
Labels: feature

#40 UE 54 Project create test
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
  src/test/java/com/isfive/usearth/web/project/RewardControllerTest.java
Labels: test
