Repository Team-ISFive/UsEarth_ISFive, pull requests merged in 2023-09, with the labels that each got.

#42 Ue 56 funding refactor
  src/main/java/com/isfive/usearth/domain/funding/dto/PaymentRegister.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Delivery.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Funding.java
  src/main/java/com/isfive/usearth/domain/funding/entity/FundingRewardSku.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Payment.java
  src/main/java/com/isfive/usearth/domain/funding/service/FundingService.java
  src/main/java/com/isfive/usearth/web/common/ControllerAdvice.java
  src/main/java/com/isfive/usearth/web/funding/FundingController.java
  src/main/java/com/isfive/usearth/web/funding/dto/DeliveryRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/FundingRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/PaymentRequest.java
  src/main/resources/projectImg/95d7e07f-d8a6-4bf5-9e2a-a8665c3f7c7e.jpg
  src/main/resources/projectImg/b56f1535-2429-4b6d-bdf5-ef6249e352c9.jpg
  src/main/resources/projectImg/dcc1888f-36b2-4ee7-a618-d3286812b6a0.jpg
  src/test/java/com/isfive/usearth/web/funding/FundingControllerTest.java
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
  src/test/java/com/isfive/usearth/web/project/RewardControllerTest.java
Labels: feature

#43 Ue 57 board valid
  src/main/java/com/isfive/usearth/annotation/Retry.java
  src/main/java/com/isfive/usearth/aop/RetryAspect.java
  src/main/java/com/isfive/usearth/domain/board/entity/Post.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostComment.java
  src/main/java/com/isfive/usearth/domain/board/service/PostCommentService.java
  src/main/java/com/isfive/usearth/domain/board/service/PostService.java
  src/main/java/com/isfive/usearth/domain/maker/entity/CorporateBusiness.java
  src/main/java/com/isfive/usearth/domain/maker/entity/Individual.java
  src/main/java/com/isfive/usearth/domain/maker/entity/Maker.java
  src/main/java/com/isfive/usearth/domain/maker/entity/PersonalBusiness.java
  src/main/java/com/isfive/usearth/domain/maker/service/MakerService.java
  src/main/java/com/isfive/usearth/web/board/PostCommentController.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/main/java/com/isfive/usearth/web/board/dto/PostCommentCreateRequest.java
  src/main/java/com/isfive/usearth/web/board/dto/PostCreateRequest.java
  src/main/java/com/isfive/usearth/web/common/ControllerAdvice.java
  src/main/java/com/isfive/usearth/web/maker/MakerController.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/CorporateRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/IndividualRegister.java
  src/main/java/com/isfive/usearth/web/maker/dto/register/PersonalRegister.java
  src/test/java/com/isfive/usearth/domain/project/service/ProjectServiceTest.java
Labels: feature

#45 Ue 59 funding cancel
  src/main/java/com/isfive/usearth/domain/funding/entity/Delivery.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Funding.java
  src/main/java/com/isfive/usearth/domain/funding/entity/FundingRewardSku.java
  src/main/java/com/isfive/usearth/domain/funding/entity/FundingStatus.java
  src/main/java/com/isfive/usearth/domain/funding/repository/FundingRepository.java
  src/main/java/com/isfive/usearth/domain/funding/service/FundingService.java
  src/main/java/com/isfive/usearth/domain/project/entity/RewardSku.java
  src/main/java/com/isfive/usearth/exception/ErrorCode.java
  src/main/java/com/isfive/usearth/web/funding/FundingController.java
  src/main/resources/projectImg/95d7e07f-d8a6-4bf5-9e2a-a8665c3f7c7e.jpg
  src/main/resources/projectImg/b56f1535-2429-4b6d-bdf5-ef6249e352c9.jpg
  src/main/resources/projectImg/dcc1888f-36b2-4ee7-a618-d3286812b6a0.jpg
  src/test/java/com/isfive/usearth/web/funding/FundingControllerTest.java
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
Labels: feature

#46 Ue 58 email smtp
  build.gradle
  src/main/java/com/isfive/usearth/config/EmailConfig.java
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/auth/jwt/service/CustomUserDetails.java
  src/main/java/com/isfive/usearth/domain/member/dto/MemberResponse.java
  src/main/java/com/isfive/usearth/domain/member/repository/MemberRepository.java
  src/main/java/com/isfive/usearth/domain/member/service/MemberService.java
  src/main/java/com/isfive/usearth/domain/utils/mail/MailService.java
  src/main/java/com/isfive/usearth/exception/ErrorCode.java
  src/main/java/com/isfive/usearth/web/HomeController.java
  src/main/java/com/isfive/usearth/web/auth/dto/SignInRequest.java
  src/main/java/com/isfive/usearth/web/auth/dto/SignUpRequest.java
  src/main/java/com/isfive/usearth/web/member/MemberController.java
  src/main/java/com/isfive/usearth/web/member/dto/MailAuthenticationRequest.java
  src/test/java/com/isfive/usearth/web/member/MemberControllerTest.java
Labels: feature, fix, test

#47 Ue 35 funding payment
  build.gradle
  src/main/java/com/isfive/usearth/UsEarthApplication.java
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/funding/entity/Funding.java
  src/main/java/com/isfive/usearth/domain/funding/entity/FundingRewardSku.java
  src/main/java/com/isfive/usearth/domain/funding/repository/FundingRepository.java
  src/main/java/com/isfive/usearth/domain/funding/service/PaymentService.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectResponse.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/repository/ProjectRepository.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/test/java/com/isfive/usearth/web/project/ProjectControllerTest.java
Labels: feature, test

#48 Ue 61 payment error email
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/board/dto/PostCommentResponse.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostComment.java
  src/main/java/com/isfive/usearth/domain/funding/service/PaymentService.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenFilter.java
  src/main/java/com/isfive/usearth/domain/utils/mail/MailService.java
  src/main/java/com/isfive/usearth/web/board/PostCommentController.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/main/java/com/isfive/usearth/web/funding/FundingController.java
  src/main/java/com/isfive/usearth/web/maker/MakerController.java
  src/main/java/com/isfive/usearth/web/project/RewardController.java
  src/test/java/com/isfive/usearth/web/board/PostCommentControllerTest.java
Labels: feature, fix

#49 Ue 60 refresh token redis store
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/auth/jwt/service/JpaUserDetailsManager.java
  src/main/java/com/isfive/usearth/domain/auth/jwt/service/TokenService.java
  src/main/java/com/isfive/usearth/domain/auth/oauth/service/OAuth2UserServiceImpl.java
  src/main/java/com/isfive/usearth/domain/member/entity/Member.java
  src/main/java/com/isfive/usearth/domain/member/service/MemberService.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenFilter.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenUtils.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/PermitAllURI.java
  src/main/java/com/isfive/usearth/web/auth/oauth/OAuth2SuccessHandler.java
  src/main/java/com/isfive/usearth/web/member/MemberController.java
Labels: feature, fix

#50 Ue 64 post delete
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/board/entity/Post.java
  src/main/java/com/isfive/usearth/domain/board/service/PostService.java
  src/main/java/com/isfive/usearth/exception/ErrorCode.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/test/java/com/isfive/usearth/web/board/PostControllerTest.java
Labels: feature

#52 UE 62 Input validation
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectService.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectModify.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectRegister.java
  src/main/java/com/isfive/usearth/web/project/dto/RewardRegister.java
Labels: feature

#60 Ue 68 swagger setting
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/config/SwaggerConfig.java
  src/main/java/com/isfive/usearth/domain/auth/jwt/service/TokenService.java
  src/main/java/com/isfive/usearth/domain/utils/jwt/JwtTokenUtils.java
  src/main/java/com/isfive/usearth/web/auth/dto/SignInRequest.java
  src/main/java/com/isfive/usearth/web/auth/dto/SignUpRequest.java
  src/main/java/com/isfive/usearth/web/board/PostCommentController.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/main/java/com/isfive/usearth/web/board/dto/PostCommentCreateRequest.java
  src/main/java/com/isfive/usearth/web/board/dto/PostCreateRequest.java
  src/main/java/com/isfive/usearth/web/funding/FundingController.java
  src/main/java/com/isfive/usearth/web/funding/dto/DeliveryRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/FundingRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/PaymentRequest.java
  src/main/java/com/isfive/usearth/web/funding/dto/RewardSkuRequest.java
  src/main/java/com/isfive/usearth/web/maker/MakerController.java
  src/main/java/com/isfive/usearth/web/maker/dto/MakerUpdateRequest.java
  src/main/java/com/isfive/usearth/web/maker/dto/register_request/BusinessMakerRequest.java
  src/main/java/com/isfive/usearth/web/maker/dto/register_request/MakerRegisterRequest.java
  src/main/java/com/isfive/usearth/web/member/MemberController.java
  src/main/java/com/isfive/usearth/web/member/dto/MailAuthenticationRequest.java
  src/main/java/com/isfive/usearth/web/member/dto/UpdateRequest.java
  src/main/java/com/isfive/usearth/web/project/ProjectCommentController.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
  src/main/java/com/isfive/usearth/web/project/RewardController.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectCommentCreateRegister.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectModify.java
  src/main/java/com/isfive/usearth/web/project/dto/ProjectRegister.java
  src/main/java/com/isfive/usearth/web/project/dto/RewardRegister.java
Labels: documentation

#61 Ue 69 fix exception process
  build.gradle
  src/main/java/com/isfive/usearth/config/SecurityConfig.java
  src/main/java/com/isfive/usearth/domain/auth/jwt/service/TokenService.java
  src/main/java/com/isfive/usearth/domain/member/service/MemberService.java
  src/main/java/com/isfive/usearth/web/board/PostController.java
  src/main/java/com/isfive/usearth/web/common/ControllerAdvice.java
  src/main/java/com/isfive/usearth/web/common/cookie/CookieUtils.java
  src/main/java/com/isfive/usearth/web/common/jwt/JwtTokenFilter.java
  src/main/java/com/isfive/usearth/web/common/jwt/JwtTokenUtils.java
  src/main/java/com/isfive/usearth/web/project/ProjectController.java
Labels: bug, fix

#65 fix: 게시판 댓글 조회 버그 수정
  src/main/java/com/isfive/usearth/domain/board/dto/PostCommentResponse.java
  src/main/java/com/isfive/usearth/domain/board/entity/PostComment.java
  src/main/java/com/isfive/usearth/domain/board/service/PostCommentService.java
Labels: bug, fix

#67 fix: 프로젝트 조회 시 RewardSku 조회 x
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectResponse.java
Labels: fix

#70 Ue 74 fix payment
  src/main/java/com/isfive/usearth/domain/funding/entity/Funding.java
  src/main/java/com/isfive/usearth/domain/funding/service/FundingService.java
  src/main/java/com/isfive/usearth/domain/funding/service/PaymentService.java
  src/main/java/com/isfive/usearth/domain/project/entity/Project.java
  src/main/java/com/isfive/usearth/web/funding/FundingController.java
  src/test/java/com/isfive/usearth/web/funding/FundingControllerTest.java
Labels: fix

#74 fix: 댓글 등록 권한 수정, 펀딩 오류 수정
  src/main/java/com/isfive/usearth/domain/board/service/PostCommentService.java
  src/main/java/com/isfive/usearth/domain/project/dto/ProjectCreate.java
  src/main/java/com/isfive/usearth/domain/project/service/ProjectCommentService.java
Labels: bug, fix
